return {
  -- { "telescope.nvim", enabled = false },
  { "nvim-notify", enabled = false },
  { "bufferline.nvim", enabled = false },
  { "mini.indentscope", enabled = false },
  { "vim-illuminate", enabled = false },
  { "todo-comments.nvim", enabled = false },
  -- { "neovim/nvim-lspconfig", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "folke/neodev.nvim", enabled = false },
  --  { "williamboman/mason-lspconfig.nvim", enabled = false },
  -- { "jose-elias-alvarez/null-ls.nvim", enabled = false },
  -- { "williamboman/mason.nvim", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  {
    "neoclide/coc.nvim",
    branch = "release",
    enabled = false,
  },
  -- { "L3MON4D3/LuaSnip", enabled = false },
  -- { "hrsh7th/cmp-nvim-lsp", enabled = false },
  -- { "hrsh7th/cmp-buffer", enabled = false },
  -- { "hrsh7th/cmp-path", enabled = false },
  -- { "saadparwaiz1/cmp_luasnip", enabled = false },
  -- { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
  -- { "folke/persistence.nvim", enabled = false },
}
